### ISSUE TITLE
Update spreadsheet example to match 0.8 spec

### ISSUE THREAD

**Issue by pmackay** [codeforamerica/ohana-api#298]
It seems the example tab names on https://docs.google.com/spreadsheets/d/1qkysLj5MAAvaysuac_9H0hOvTAb1aJEMhUVJAECmj2c/edit#gid=1983571683 are plural but the current spec is now singular. Plus there seem to be more tabs :)

**Comment by monfresh** [comment]
I've updated the API with the latest field name changes in the OpenReferral spec, and I've updated the [CSV Wiki](https://github.com/codeforamerica/ohana-api/wiki/Populating-the-Postgres-database-from-OpenReferral-compliant-CSV-files) with a note that there are currently a few differences between the spec and the API. Those differences only affect those who already have data and have already converted it to OpenReferral CSV files.

The Google spreadsheets template that I created is meant for people producing data from scratch, and that template is meant to be compatible with Ohana API. The two main issues you originally brought up (pluralized versus singular file names, and the various single-attribute tables) I still maintain are Open Referral issues that need to be resolved there. I've opened those issues against OpenReferral 1.0: https://github.com/codeforamerica/OpenReferral/issues/78 and https://github.com/codeforamerica/OpenReferral/issues/76.

So, since the issue was originally opened against the spreadsheet, which is meant to be Ohana API-compatible, and has always been, I'm closing this. Any remaining discrepancies between the spec and Ohana would need to be resolved by the user when they write their script that produces CSV files, or by the Ohana API import script. Contributions in the form of scripts that transform data between the spec and what the Ohana API app expects are always welcome.

**Comment by pmackay** [comment]
OK. Do you think there is merit in having a spreadsheet template that matches OR? I could open an issue on OR about that. Its an odd one because its useful for importing into Ohana (and hence needs to match API), but also the OR spec defines the table structure, so a reference example would be useful matching that too....

**Comment by monfresh** [comment]
Yes, I think there is merit in having an OR template. It would be most helpful to those who are producing data from scratch by entering it in the spreadsheet, and who are not planning on importing it into Ohana. I'm not sure if we've come across this use case yet.
