### ISSUE TITLE
Backup to CSV

### ISSUE THREAD

**Issue by devinbalkind** [codeforamerica/ohana-api#304]
*feature request

It would be great if we could dump all our Ohana data into a CSV, or maybe JSON, format.

We'd be using that feature right now to do some bulk data cleaning.  

We imported our data into Ohana, used the interface to categorize services, and then discovered that our location information didn't get imported correctly and needs to be imported again.  If we import it again, we'll lose all the changes we made through the interface.  If we could export it, then we could probably clean the data and import again without losing our previous work.

**Comment by monfresh** [comment]
What exactly didn't get imported correctly and that you can't fix directly in the admin interface?

**Comment by volkanunsal** [comment]
I can answer this. We imported the data before there was a csv importer. Everything was imported correctly, but it looks like the addresses have gone missing between then and now. That's why we don't have any locations on the map anymore. What could have caused this? The only thing I've done on the backend is to run the migrations, and nothing else.

**Comment by monfresh** [comment]
When you say the addresses are gone, do you mean the Addresses table in the database is empty?

**Comment by volkanunsal** [comment]
Yeah, the table is still there.

**Comment by monfresh** [comment]
I can't think of anything that would delete addresses from the table, but if there are indeed no addresses in the database, I would recommend adding the addresses manually using the admin interface. This is the easiest and probably the safest option.

**Comment by monfresh** [comment]
In the meantime, I will work on adding a CSV export option.

**Comment by pmackay** [comment]
@monfresh a requirement being asked for on a project we're ramping up into is for admin-type users to be able to download custom CSV files defined by some selection criteria. Could that related to this about backup? Or would that be a more logical fit in the web-search frontend UI?

Related to this have you considered using http://activeadmin.info/ or similar to provide batch operations?

**Comment by monfresh** [comment]
What I'm working on right now is a bulk download of each individual table in CSV format. The best tool for the job that I've found so far is the [csv_shaper](https://github.com/paulspringett/csv_shaper) gem. It's lightweight and allows you to easily customize the output without having to define new methods on a Model.

I tried both Active Admin and RailsAdmin during the initial development of the project, and neither fit our needs. I found it was easier, more flexible, and more maintainable to write the admin interface from scratch using the built-in Rails functionality rather than depending on a bloated external tool.

**Comment by pmackay** [comment]
@monfresh would really appreciate it if you could give a little more detail about why ActiveAdmin and RailsAdmin were not fit for purpose? What specific needs were outside their scope?

thanks!

**Comment by monfresh** [comment]
It's been almost 2 years, so I don't remember all the exact details, but I remember running into lots of issues with Active Admin back when we were using Mongoid, such as basic functionality being broken. I don't remember if I tried RailsAdmin with Mongoid or Postgres, but it was very hard to customize in terms of nested forms, and especially the taxonomy checkboxes. I can confidently say that I spent a lot more time trying to get Active Admin and RailsAdmin to work than building the initial admin interface from scratch.

Now that we have a working admin interface, if we want to add functionality to it, I think it makes most sense to find a lightweight gem that solves that specific problem, or build it ourselves if it's not too complicated, as opposed to using a heavyweight gem that comes with lots of stuff that we won't ever use, but that will still increase the app's memory footprint.

Obviously, in your own deployment of Ohana API, you're free to do as you please with the admin interface. If Active Admin makes sense for you to use, by all means go for it.

**Comment by pmackay** [comment]
@monfresh just to ask a bit more about CSV download, are you considering turning it into a datapackage, possibly with a JSON metadata file? Is that the kind of thing to be encouraged across the ecosystem (i.e. to promote to others)?

**Comment by monfresh** [comment]
I'm not opposed to adding a `datapackage.json`, but it's not part of what I'm doing to solve this particular issue. If you're referring to data packages as defined by [Open Knowledge](http://data.okfn.org/standards), then my understanding is that the purpose of a `datapackage.json` is to provide a description of the data when it would otherwise not be available to consumers of the data.

In this case, we are dealing with a standard that is already well-defined and well-described, and that already comes with a [datapackage.json](https://github.com/codeforamerica/OpenReferral/blob/master/datapackage.json) describing the data, so I don't see the immediate benefit of including it with the CSV downloads.

I suppose it would be worth adding if the data contains extra fields that aren't in the default Open Referral spec. I just tried the [DataPacakage.json Creator](http://data.okfn.org/tools/create) tool with an Ohana API CSV, and it didn't properly detect the correct type of certain fields. So, unless there was a more reliable tool to automatically generate the `datapackage.json`, you (as a producer of the data) would need to generate and edit it manually using a tool like the one mentioned above.

From my quick search, I couldn't find any Ruby/Rails tools that can create a `datapackage.json` from a DB, and I don't think it's worth developing our own for Ohana API.

**Comment by pmackay** [comment]
Just to check, do you plan to implement a way to build a zip of all the CSV
files?

**Comment by monfresh** [comment]
Yes sir.
