### ISSUE TITLE
Support query parameters for level of detail returned in search results

### ISSUE THREAD

**Issue by jesserosato** [codeforamerica/ohana-api#306]
Would it be possible to support query parameters that would allow API search requests to specify the amount of detail needed in the response? My use case is a search application that maps social services using an Ohana API instance as a data source ([benefisher](http://github.com/code4sac/benefisher)). We want users to be able to see at a glance if a location is open, but hours are not included in the location objects returned from a search query. It would be useful to be able to request those fields using a query parameter. I've never really played with Ruby, but I'd be willing to try it or pitch it to our brigade if there's an interest in this.

Thanks, and thanks for all your awesome work on this proejct.

**Comment by monfresh** [comment]
Hi @jesserosato. Thanks for using Ohana API!

The easiest way to customize which attributes are returned by the API is to edit the various [serializers](https://github.com/codeforamerica/ohana-api/tree/master/app/serializers). In your case, you would want to edit the [locations_serializer](https://github.com/codeforamerica/ohana-api/blob/master/app/serializers/locations_serializer.rb#L9) by adding the following 2 lines after line 8:
```ruby
has_many :regular_schedules
has_many :holiday_schedules
```
Then remove those same 2 lines from [location_serializer](https://github.com/codeforamerica/ohana-api/blob/master/app/serializers/location_serializer.rb#L6-7).

Being able to allow clients to specify which attributes they want to receive from the API would be a nice feature, but it's not trivial to implement.

Ideally, an app like benefisher would allow users to filter locations by open status, so that they don't have to read the hours to figure out whether or not the location is open. This is something that I'm planning on adding soonish.

**Comment by jesserosato** [comment]
Thanks for the quick response! We'll give your suggestions a try!



—

**Comment by monfresh** [comment]
You're welcome. I hope it helped. I've also added a Wiki page explaining how to customize the JSON output: https://github.com/codeforamerica/ohana-api/wiki/Customizing-the-attributes-returned-by-the-API
