### ISSUE TITLE
Admin with no ties to any entities should not see the "Add a new program" button.

### ISSUE THREAD

**Issue by devinbalkind** [codeforamerica/ohana-api#308]
When I created a new admin user and clicked on the various entity tabs, I noticed there were no "Add" buttons except for "Add a New Program" on Programs page (/admin/programs).  

Clicking that button generates an error: translation missing: en.admin.not_authorized

I'd imagine that button should be removed for new admins without any services/data assigned to them.

Not a high priority IMHO.

**Comment by monfresh** [comment]
Thanks for the report. How did you create the new admin, and how does your `config/locales/en.yml` compare to the [latest one](https://github.com/codeforamerica/ohana-api/blob/master/config/locales/en.yml)?

**Comment by devinbalkind** [comment]
I just registered an account through the sign in process.

I've gotta pass Any .yml questions to @volkanunsal and @gl2748

**Comment by monfresh** [comment]
@devinbalkind It looks like your version of the app is not up to date, which is why you saw that `translation missing` error. Bugs should be reported against the latest code, which you can test on our demo website.

As for the brand new admin seeing an "Add a new program" button, that is indeed a bug, which I will fix soon.
