### ISSUE TITLE
Best way to import content via an external API?

### ISSUE THREAD

**Issue by pmackay** [codeforamerica/ohana-api#324]
@monfresh can you offer any advice on the best way to approach customising Ohana to support importing content directly from an external API? Do you know of any instances where that's been done before? 

Specifically the `*Importer` classes under `lib` are oriented around file imports. Would it make most sense to save data from an API call to a CSV, to reuse that logic? Or just code up a more direct method of saving data?

thanks!

**Comment by monfresh** [comment]
I do not know of anyone who has tried that before. The idea behind the importer is that is based on the Open Referral standard, which is a set of CSV files, so yes, I think it makes most sense to save the data to CSV first. It's best not to add any dependencies to the import process, especially ones that require an internet connection and an uninterrupted connection to an external API.

Ideally, your instance of Ohana API should be the canonical source of the data, so you shouldn't have to rely on an external source for the data, and so there aren't two APIs serving the same data.

**Comment by greggish** [comment]
I understand that canonical data was what the Ohana team originally
envisioned, but I think that the reality of most circumstances is that
resource directory data is aggregated by different kinds of institutions,
and thus a best case scenario would be for an ecosystem of APIs to publish
in the Open Referral format. In which case the ability for Ohana to pull
data via other APIs -- if at all technically feasible -- will be important.

I don't know the technical answer to this but believe it's very much worth
exploring.

**Comment by md5** [comment]
@greggish :+1:

**Comment by monfresh** [comment]
The technical answer to this already exists. Ohana API is able to import Open Referral-compliant CSV files. So, if there are multiple institutions publishing in the Open Referral format, that means they have CSV files available to download, which can then be imported into Ohana API.

If the institution that you want to pull data from is not publishing in the Open Referral format, and is using their own custom API, then you will need to write your own ETL script to interface with that API. My recommendation is to separate the extraction and transformation from the loading because Ohana API already takes care of the loading part. The interaction with the external API will be to create CSV files from the data. Once the files are ready, Ohana API's built-in import tools can then be used.

**Comment by monfresh** [comment]
I'm closing this to keep the issue list clean, but feel free to keep the discussion going if you have any other questions or concerns.
