### ISSUE TITLE
Trouble with CSV import

### ISSUE THREAD

**Issue by pmackay** [codeforamerica/ohana-api#332]
I'm seeing the output below when importing a set of CSVs. The `Organization can't be blank for Location` message is presumably because from the Rails console I cannot see any Organizations in the database. However it seems like that stage completed. When are rows actually saved to the database?

```
Importing your organizations...
accreditations column is missing
date_incorporated column is missing
funding_sources column is missing
licenses column is missing
website column is missing
Importing your programs...
Importing your locations and addresses...
accessibility column is missing
admin_emails column is missing
email column is missing
languages column is missing
virtual column is missing
website column is missing
Line 2: Organization can't be blank for Location
Line 3: Organization can't be blank for Location
Line 4: Organization can't be blank for Location
```

Any tips much appreciated!

**Comment by monfresh** [comment]
The import script saves valid records to the database and outputs an error message for invalid records. It does not completely stop the entire process when it reaches the first error.

If you look at the output during the organizations import, you will see many errors about missing columns. The CSV file must be valid in order to import its contents. One of the rules is that is must contain all of the column headers, and they have to spelled exactly like in the Wiki documentation. The [Google spreadsheets template](https://docs.google.com/spreadsheets/d/1qkysLj5MAAvaysuac_9H0hOvTAb1aJEMhUVJAECmj2c/edit#gid=0) that we provide helps ensure that the CSV files themselves are valid.

**Comment by pmackay** [comment]
A couple of things on this:

Why do optional columns need to be present in a CSV file? 

And more significantly, could the process output a message to explicitly say the organisation (or any other phase) failed, if it did? Its impossible to know that and whether the other messages are warnings or errors. It might also make sense to stop the import if one part fails, especially as locations/addresses depend on organisations.

**Comment by monfresh** [comment]
The headers themselves are not optional. Only the values within each row are optional. We need to ensure that only HSDS-defined column names (headers) are present, and the best way to do that is to require that all the headers be present. Otherwise, if we didn't check for the presence of `accreditations` for example, and if your data includes accreditations for some or all organizations, how would we be able to know for sure that the values correspond to the `accreditations` column? Perhaps you misspelled it or called it something else, and the best way to check for that would be to restrict the headers to a specific set of values. Can you think of a better way to validate the column names?

Furthermore, including all possible columns is a form of documentation and keeps things consistent. If you were to exchange your data with someone else who isn't familiar with HSDS, you would want to include all columns, even if they were empty, so that they can see what kind of information is supported by HSDS.

As for the output, I wouldn't say that it's "impossible" to know. Words such as "is missing" are usually an indication of a problem, but I agree it could be worded differently. There aren't any warnings during the import, only notifications and errors. It notifies you when an import is taking place, and if an error occurs, it lists it, along with the offending row in the CSV file.

For the missing headers, I think a better error would be `header [header name] is required, but is missing`. Adding a notification before that, such as `Verifying headers...`, would be helpful too I think. I also agree that if the headers are invalid, it should stop the process since you can't continue without organizations. The script is a collection of rake tasks, and off the top of my head, I'm not sure if there's a way to abort in between tasks, but in the meantime, you can import each CSV file individually. For example:
```
bin/rake import:organizations
```

**Comment by monfresh** [comment]
I think the best thing to do is to move the header verification into the [FileChecker](https://github.com/codeforamerica/ohana-api/blob/master/lib/file_checker.rb) class since checking headers is a type of file verification. Once we know the files are valid, then we can proceed with verifying the data.

**Comment by pmackay** [comment]
Thinking on this more and your comments, I agree it makes sense to require all column headers. 

For output logging, "impossible" was a bit strong but I guess it wasnt obvious to me, I had to go checking the database content. Is a logging framework used? Could the messages be classified as ERROR or WARNING? (any message that starts with `ERROR: ` is a much clearer indication). 

Also important to distinguish between single row errors or the whole thing. If just one row fails, does the entire import fail?

A message at the end saying "organisation import failed" and/or not proceeding with other imports would be super helpful.

Agree about place to do header verification. I'm not currently sure about how true this is now, but could the import code be designed such that imports could be handled via different methods, with files being one of them?

**Comment by monfresh** [comment]
I improved the error messages, and made the script abort when required files are missing or empty, and when headers are invalid. You can review the changes here: https://github.com/codeforamerica/ohana-api/blob/332-improve-import-errors/lib/file_checker.rb#L7-14

I don't think explicitly saying `ERROR` is necessary since the message itself describes the situation pretty clearly in my opinion. Let me know if you disagree.

> could the import code be designed such that imports could be handled via different methods, with files being one of them?

I'm not sure what you're asking here, but the basic code is in the [EntityImporter](https://github.com/codeforamerica/ohana-api/blob/332-improve-import-errors/lib/entity_importer.rb) and the `FileChecker` that I linked to above.

**Comment by pmackay** [comment]
Also just noticing that 

```
Importing your locations and addresses...
accessibility column is missing
admin_emails column is missing
email column is missing
languages column is missing
virtual column is missing
website column is missing
```

makes it tough to know which table those "column is missing" messages relate to, because 2 tables are imported in same step. Not sure if your recent changes would affect this. Do 2 tables need to be imported in 1 step?

**Comment by pmackay** [comment]
It would be really helpful if there could be an option on the command line that allowed valid rows to be imported and only exclude others, not fail the whole import of a file because of one wrong entry. This is different to the headers being wrong which is a logical fail for whole file.

I could raise a separate issue on that if helpful.
