### ISSUE TITLE
Repeated listings when setting service_area

### ISSUE THREAD

**Issue by cderenburger** [codeforamerica/ohana-api#357]
I'm having an issue with repeated listings when including <code>&service_area=*County*</code>
I just merged from the master branch at https://github.com/codeforamerica/ohana-api to bring my local installation up to date.  I'm pretty sure this was working correctly a few days ago before having synced with the repo.  When running <code>git diff upstream/master</code> with my current branch the only differences are in my database.yml and settings.yml.

The url address below is <code>http://elizabeth.duckdns.org:4000/locations?keyword=Food+Pantries&service_area=Clallam</code>
![tafy](https://cloud.githubusercontent.com/assets/13293901/9291056/9fedaeac-4360-11e5-9002-00a3ac28b322.jpg)

I reset and re-imported my data to see if that was the issue, same problem.  When viewing the service record in <code>localhost:8080/admin</code> the service_area is only listed once in the service record.

The record "The Answer for Youth" has 5 services, and is seen repeating 5 times.  The same happens with other agencies.  I checked my taxonomy for each service record and each does have different taxonomy codes selected.

If I do not use <code>&service_area=*County*</code> and instead use <code>&location=port angeles</code> I get the expected result of one listing for the service.

Anyone else having this issue?

**Comment by cderenburger** [comment]
This problem with <code>&service_area=</code> occurs with the <code>&keyword=</code> search.  If I leave keyword blank and instead set <code>&category[]=Food Pantries</code> with the search_area the search results are correct.

**Comment by monfresh** [comment]
Thanks for reporting this. This is probably due to removing the `.uniq` at the end of the search method in this commit: https://github.com/codeforamerica/ohana-api/commit/ae238e8f5bce110e8b268398c379fdcd83a6e15c

I couldn't remember why we needed the `.uniq`, and all tests passed, so I thought we could remove it, but apparently not. I'll make sure to add a test for this scenario and see if I can reproduce it.

**Comment by monfresh** [comment]
I've identified the issue. It happens when the `service_area` parameter is used and a location has multiple services with service areas that match the search term. No other parameter is required to reproduce this issue. Next step is to figure out how to fix this.

**Comment by cderenburger** [comment]
Is it possible to just return the specific service record at the location that matches rather than all the services at the location?

**Comment by monfresh** [comment]
Search returns Location objects. What you are seeing in the results is the same Location repeated, not multiple services. The solution is to use `group` to eliminate duplicates in the `service_area` query, but it is interfering with the location search due to a [known issue with the geocoder gem](https://github.com/alexreisner/geocoder#known-issue). I'm trying to figure out the best way to solve this.

**Comment by monfresh** [comment]
I just fixed this. Could you grab the latest changes and try it again, please?

**Comment by cderenburger** [comment]
This works great here.  Thanks @monfresh.
